// packages/@livestore/solid/src/LiveStoreProvider.tsx
import type { Adapter, BootStatus, IntentionalShutdownCause, MigrationsReport, SyncError } from '@livestore/common'
import { provideOtel, UnexpectedError } from '@livestore/common'
import type { LiveStoreSchema } from '@livestore/common/schema'
import type {
  CreateStoreOptions,
  OtelOptions,
  ShutdownDeferred,
  Store,
  LiveStoreContext as StoreContext_,
} from '@livestore/livestore'
import { createStore, makeShutdownDeferred, StoreInterrupted } from '@livestore/livestore'
import { errorToString, LS_DEV, omitUndefineds } from '@livestore/utils'
import type { OtelTracer } from '@livestore/utils/effect'
import {
  Cause,
  Deferred,
  Effect,
  Exit,
  identity,
  Logger,
  LogLevel,
  Schema,
  Scope,
  TaskTracing,
} from '@livestore/utils/effect'
import type * as otel from '@opentelemetry/api'
import {
  createEffect,
  createRenderEffect,
  type JSX,
  Match,
  mergeProps,
  on,
  onCleanup,
  type ParentProps,
  Switch,
} from 'solid-js'
import { createStore as createSolidStore } from 'solid-js/store'
import { LiveStoreContext } from './LiveStoreContext.ts'

export interface LiveStoreProviderProps {
  schema: LiveStoreSchema
  /**
   * The `storeId` can be used to isolate multiple stores from each other.
   * So it can be useful for multi-tenancy scenarios.
   *
   * The `storeId` is also used for persistence.
   *
   * Make sure to also configure `storeId` in LiveStore Devtools (e.g. in Vite plugin).
   *
   * @default 'default'
   */
  storeId?: string
  boot?: (
    store: Store<LiveStoreSchema>,
    ctx: { migrationsReport: MigrationsReport; parentSpan: otel.Span },
  ) => void | Promise<void> | Effect.Effect<void, unknown, OtelTracer.OtelTracer>
  otelOptions?: Partial<OtelOptions>
  renderLoading?: (status: BootStatus) => JSX.Element
  renderError?: (error: UnexpectedError | unknown) => JSX.Element
  renderShutdown?: (cause: IntentionalShutdownCause | StoreInterrupted | SyncError) => JSX.Element
  adapter: Adapter
  /**
   * In order for LiveStore to apply multiple events in a single render,
   * you need to pass the `batchUpdates` function from either `react-dom` or `react-native`.
   *
   * ```ts
   * // With React DOM
   * import { unstable_batchedUpdates as batchUpdates } from 'react-dom'
   *
   * // With React Native
   * import { unstable_batchedUpdates as batchUpdates } from 'react-native'
   * ```
   */
  batchUpdates: (run: () => void) => void
  disableDevtools?: boolean
  signal?: AbortSignal
  /**
   * Currently only used in the web adapter:
   * If true, registers a beforeunload event listener to confirm unsaved changes.
   *
   * @default true
   */
  confirmUnsavedChanges?: boolean
  /**
   * Payload that will be passed to the sync backend when connecting
   *
   * @default undefined
   */
  syncPayload?: Schema.JsonValue
  debug?: {
    instanceId?: string
  }
}

const defaultRenderError = (error: UnexpectedError | unknown) =>
  Schema.is(UnexpectedError)(error) ? error.toString() : errorToString(error)

const defaultRenderShutdown = (cause: IntentionalShutdownCause | StoreInterrupted | SyncError) => {
  const reason =
    cause._tag === 'LiveStore.StoreInterrupted'
      ? `interrupted due to: ${cause.reason}`
      : cause._tag === 'InvalidPushError' || cause._tag === 'InvalidPullError'
        ? `sync error: ${cause.cause}`
        : cause.reason === 'devtools-import'
          ? 'devtools import'
          : cause.reason === 'devtools-reset'
            ? 'devtools reset'
            : cause.reason === 'adapter-reset'
              ? 'adapter reset'
              : cause.reason === 'manual'
                ? 'manual shutdown'
                : 'unknown reason'

  return <>LiveStore Shutdown due to {reason}</>
}

const defaultRenderLoading = (status: BootStatus) => <>LiveStore is loading ({status.stage})...</>

export const LiveStoreProvider = (props: LiveStoreProviderProps & ParentProps) => {
  const config = mergeProps(
    {
      renderLoading: defaultRenderLoading,
      renderError: defaultRenderError,
      renderShutdown: defaultRenderShutdown,
      storeId: 'default',
      confirmUnsavedChanges: true,
    },
    props,
  )
  const storeCtx = useCreateStore({
    storeId: config.storeId,
    schema: config.schema,
    adapter: config.adapter,
    batchUpdates: config.batchUpdates,
    confirmUnsavedChanges: config.confirmUnsavedChanges,
    ...omitUndefineds({
      otelOptions: config.otelOptions,
      boot: config.boot,
      disableDevtools: config.disableDevtools,
      signal: config.signal,
      syncPayload: config.syncPayload,
      debug: config.debug,
    }),
  })

  return (
    <Switch>
      <Match when={storeCtx.stage === 'error' && storeCtx}>{(ctx) => config.renderError(ctx().error)}</Match>
      <Match when={storeCtx.stage === 'shutdown' && storeCtx}>{(ctx) => config.renderShutdown(ctx().cause)}</Match>
      <Match when={storeCtx.stage === 'running' && storeCtx}>
        {(ctx) => {
          globalThis.__debugLiveStore ??= {}
          if (Object.keys(globalThis.__debugLiveStore).length === 0) {
            globalThis.__debugLiveStore._ = ctx().store
          }
          globalThis.__debugLiveStore[config.debug?.instanceId ?? config.storeId] = ctx().store
          return <LiveStoreContext.Provider value={storeCtx as TODO}>{config.children}</LiveStoreContext.Provider>
        }}
      </Match>
      <Match
        when={
          // SOLID  - these checks are technically redundant
          //          but otherwise the types aren't inferred and we would have to typecast to BootStatus
          storeCtx.stage !== 'error' && storeCtx.stage !== 'shutdown' && storeCtx.stage !== 'running' && storeCtx
        }
      >
        {(ctx) => config.renderLoading(ctx())}
      </Match>
    </Switch>
  )
}

type UseCreateStoreOptions = CreateStoreOptions<LiveStoreSchema> & {
  signal?: AbortSignal
  otelOptions?: Partial<OtelOptions>
}

const useCreateStore = (options: UseCreateStoreOptions) => {
  const [context, setContext] = createSolidStore<{
    value: StoreContext_ | BootStatus
    componentScope: Scope.CloseableScope | undefined
    shutdownDeferred: ShutdownDeferred | undefined
    /** Used to wait for the previous shutdown deferred to fully complete before creating a new one */
    previousShutdownDeferred: ShutdownDeferred | undefined
    counter: number
  }>({
    value: { stage: 'loading' },
    componentScope: undefined,
    shutdownDeferred: undefined,
    previousShutdownDeferred: undefined,
    counter: 0,
  })

  const interrupt = (
    componentScope: Scope.CloseableScope,
    shutdownDeferred: ShutdownDeferred,
    error: StoreInterrupted,
  ) =>
    Effect.gen(function* () {
      // console.log('[@livestore/livestore/react] interupting', error)
      yield* Scope.close(componentScope, Exit.fail(error))
      yield* Deferred.fail(shutdownDeferred, error)
    }).pipe(
      Effect.tapErrorCause((cause) => Effect.logDebug('[@livestore/livestore/react] interupting', cause)),
      Effect.runFork,
    )

  createRenderEffect(
    on(
      () => ({ ...options }),
      () => {
        if (context.componentScope !== undefined && context.shutdownDeferred !== undefined) {
          interrupt(
            context.componentScope,
            context.shutdownDeferred,
            new StoreInterrupted({
              reason: `re-rendering due to changed input props: ${''}`,
            }),
          )

          setContext({
            componentScope: undefined,
            shutdownDeferred: undefined,
          })
        }

        setContext((context) => ({
          value: { stage: 'loading' },
          componentScope: undefined,
          shutdownDeferred: undefined,
          previousShutdownDeferred: context.shutdownDeferred,
          counter: context.counter + 1,
        }))
      },
    ),
  )

  createEffect(() => {
    const counter = context.counter

    const setContextValue = (value: StoreContext_ | BootStatus) => {
      if (context.counter !== counter) return
      setContext({ value })
    }

    options.signal?.addEventListener('abort', () => {
      if (
        context.componentScope !== undefined &&
        context.shutdownDeferred !== undefined &&
        context.counter === counter
      ) {
        interrupt(
          context.componentScope,
          context.shutdownDeferred,
          new StoreInterrupted({ reason: 'Aborted via provided AbortController' }),
        )
        setContext({
          componentScope: undefined,
          shutdownDeferred: undefined,
        })
      }
    })

    const cancelStore = createCancelStore(context, setContext, setContextValue, options)

    onCleanup(() => {
      cancelStore()

      if (context.componentScope !== undefined && context.shutdownDeferred !== undefined) {
        interrupt(
          context.componentScope,
          context.shutdownDeferred,
          new StoreInterrupted({ reason: 'unmounting component' }),
        )
        setContext({
          componentScope: undefined,
          shutdownDeferred: undefined,
        })
      }
    })
  })

  return context.value
}

interface Context {
  value: StoreContext_ | BootStatus
  componentScope: Scope.CloseableScope | undefined
  shutdownDeferred: ShutdownDeferred | undefined
  /** Used to wait for the previous shutdown deferred to fully complete before creating a new one */
  previousShutdownDeferred: ShutdownDeferred | undefined
  counter: number
}

type MakeOptional<T, TKeys extends keyof T> = Omit<T, TKeys> & { [TKey in TKeys]: T[TKey] | undefined }

const createCancelStore = (
  context: Context,
  setContext: (context: Partial<Context>) => void,
  setContextValue: (value: StoreContext_ | BootStatus) => void,
  options: MakeOptional<
    UseCreateStoreOptions,
    | 'batchUpdates'
    | 'boot'
    | 'confirmUnsavedChanges'
    | 'context'
    | 'debug'
    | 'disableDevtools'
    | 'otelOptions'
    | 'params'
    | 'signal'
    | 'syncPayload'
  >,
) => {
  return Effect.gen(function* () {
    // Wait for the previous store to fully shutdown before creating a new one
    if (context.previousShutdownDeferred) {
      yield* Deferred.await(context.previousShutdownDeferred)
    }

    const componentScope = yield* Scope.make().pipe(Effect.acquireRelease(Scope.close))
    const shutdownDeferred = yield* makeShutdownDeferred

    setContext({
      componentScope,
      shutdownDeferred,
    })

    yield* Effect.gen(function* () {
      const store = yield* createStore({
        schema: options.schema,
        storeId: options.storeId,
        adapter: options.adapter,
        shutdownDeferred,
        ...omitUndefineds({
          boot: options.boot,
          batchUpdates: options.batchUpdates,
          disableDevtools: options.disableDevtools,
          context: options.context,
          params: options.params,
          confirmUnsavedChanges: options.confirmUnsavedChanges,
          syncPayload: options.syncPayload,
        }),
        onBootStatus: (status) => {
          if (context.value.stage === 'running' || context.value.stage === 'error') return
          // NOTE sometimes when status come in in rapid succession, only the last value will be rendered by React
          setContextValue(status)
        },
        debug: { ...omitUndefineds({ instanceId: options.debug?.instanceId }) },
      }).pipe(Effect.tapErrorCause((cause) => Deferred.failCause(shutdownDeferred, cause)))

      setContextValue({ stage: 'running', store })
    }).pipe(Scope.extend(componentScope), Effect.forkIn(componentScope))

    const shutdownContext = (cause: IntentionalShutdownCause | StoreInterrupted | SyncError) =>
      Effect.sync(() => setContextValue({ stage: 'shutdown', cause }))

    yield* Deferred.await(shutdownDeferred).pipe(
      Effect.tapErrorCause((cause) => Effect.logDebug('[@livestore/livestore/react] shutdown', Cause.pretty(cause))),
      Effect.tap((intentionalShutdown) => shutdownContext(intentionalShutdown)),
      Effect.catchTag('InvalidPushError', (cause) => shutdownContext(cause)),
      Effect.catchTag('InvalidPullError', (cause) => shutdownContext(cause)),
      Effect.catchTag('LiveStore.StoreInterrupted', (cause) => shutdownContext(cause)),
      Effect.tapError((error) => Effect.sync(() => setContextValue({ stage: 'error', error }))),
      Effect.tapDefect((defect) => Effect.sync(() => setContextValue({ stage: 'error', error: defect }))),
      Effect.exit,
    )
  }).pipe(
    Effect.scoped,
    Effect.withSpan('@livestore/react:useCreateStore'),
    LS_DEV ? TaskTracing.withAsyncTaggingTracing((name: string) => (console as any).createTask(name)) : identity,
    provideOtel(
      omitUndefineds({
        parentSpanContext: options.otelOptions?.rootSpanContext,
        otelTracer: options.otelOptions?.tracer,
      }),
    ),
    Effect.tapCauseLogPretty,
    Effect.annotateLogs({ thread: 'window' }),
    Effect.provide(Logger.prettyWithThread('window')),
    Logger.withMinimumLogLevel(LogLevel.Debug),
    Effect.runCallback,
  )
}

// packages/@livestore/react/src/LiveStoreProvider.tsx
import type { Adapter, BootStatus, IntentionalShutdownCause, MigrationsReport } from '@livestore/common'
import { provideOtel, UnexpectedError } from '@livestore/common'
import type { LiveStoreSchema } from '@livestore/common/schema'
import type {
  CreateStoreOptions,
  LiveStoreContext as StoreContext_,
  OtelOptions,
  ShutdownDeferred,
  Store,
} from '@livestore/livestore'
import { createStore, makeShutdownDeferred, StoreInterrupted } from '@livestore/livestore'
import { errorToString, IS_REACT_NATIVE, LS_DEV } from '@livestore/utils'
import type { OtelTracer } from '@livestore/utils/effect'
import {
  Cause,
  Deferred,
  Effect,
  Exit,
  identity,
  Logger,
  LogLevel,
  Schema,
  Scope,
  TaskTracing,
} from '@livestore/utils/effect'
import type * as otel from '@opentelemetry/api'
import type { ReactElement, ReactNode } from 'react'
import React from 'react'

import { LiveStoreContext } from './LiveStoreContext.js'

export interface LiveStoreProviderProps {
  schema: LiveStoreSchema
  /**
   * The `storeId` can be used to isolate multiple stores from each other.
   * So it can be useful for multi-tenancy scenarios.
   *
   * The `storeId` is also used for persistence.
   *
   * Make sure to also configure `storeId` in LiveStore Devtools (e.g. in Vite plugin).
   *
   * @default 'default'
   */
  storeId?: string | undefined
  boot?: (
    store: Store<LiveStoreSchema>,
    ctx: { migrationsReport: MigrationsReport; parentSpan: otel.Span },
  ) => void | Promise<void> | Effect.Effect<void, unknown, OtelTracer.OtelTracer>
  otelOptions?: Partial<OtelOptions>
  renderLoading?: (status: BootStatus) => ReactElement
  renderError?: (error: UnexpectedError | unknown) => ReactElement
  renderShutdown?: (cause: IntentionalShutdownCause | StoreInterrupted) => ReactElement
  adapter: Adapter
  /**
   * In order for LiveStore to apply multiple events in a single render,
   * you need to pass the `batchUpdates` function from either `react-dom` or `react-native`.
   *
   * ```ts
   * // With React DOM
   * import { unstable_batchedUpdates as batchUpdates } from 'react-dom'
   *
   * // With React Native
   * import { unstable_batchedUpdates as batchUpdates } from 'react-native'
   * ```
   */
  batchUpdates: (run: () => void) => void
  disableDevtools?: boolean
  signal?: AbortSignal
  /**
   * Currently only used in the web adapter:
   * If true, registers a beforeunload event listener to confirm unsaved changes.
   *
   * @default true
   */
  confirmUnsavedChanges?: boolean
  /**
   * Payload that will be passed to the sync backend when connecting
   *
   * @default undefined
   */
  syncPayload?: Schema.JsonValue
  debug?: {
    instanceId?: string
  }
}

const defaultRenderError = (error: UnexpectedError | unknown) =>
  IS_REACT_NATIVE ? <></> : <>{Schema.is(UnexpectedError)(error) ? error.toString() : errorToString(error)}</>

const defaultRenderShutdown = (cause: IntentionalShutdownCause | StoreInterrupted) => {
  const reason =
    cause._tag === 'LiveStore.StoreInterrupted'
      ? `interrupted due to: ${cause.reason}`
      : cause.reason === 'devtools-import'
        ? 'devtools import'
        : cause.reason === 'devtools-reset'
          ? 'devtools reset'
          : cause.reason === 'adapter-reset'
            ? 'adapter reset'
            : cause.reason === 'manual'
              ? 'manual shutdown'
              : 'unknown reason'

  return IS_REACT_NATIVE ? <></> : <>LiveStore Shutdown due to {reason}</>
}

const defaultRenderLoading = (status: BootStatus) =>
  IS_REACT_NATIVE ? <></> : <>LiveStore is loading ({status.stage})...</>

export const LiveStoreProvider = ({
  renderLoading = defaultRenderLoading,
  renderError = defaultRenderError,
  renderShutdown = defaultRenderShutdown,
  otelOptions,
  children,
  schema,
  storeId = 'default',
  boot,
  adapter,
  batchUpdates,
  disableDevtools,
  signal,
  confirmUnsavedChanges = true,
  syncPayload,
  debug,
}: LiveStoreProviderProps & { children?: ReactNode }): React.ReactElement => {
  const storeCtx = useCreateStore({
    storeId,
    schema,
    otelOptions,
    boot,
    adapter,
    batchUpdates,
    disableDevtools,
    signal,
    confirmUnsavedChanges,
    syncPayload,
    debug,
  })

  if (storeCtx.stage === 'error') {
    return renderError(storeCtx.error)
  }

  if (storeCtx.stage === 'shutdown') {
    return renderShutdown(storeCtx.cause)
  }

  if (storeCtx.stage !== 'running') {
    return renderLoading(storeCtx)
  }

  globalThis.__debugLiveStore ??= {}
  if (Object.keys(globalThis.__debugLiveStore).length === 0) {
    globalThis.__debugLiveStore['_'] = storeCtx.store
  }
  globalThis.__debugLiveStore[debug?.instanceId ?? storeId] = storeCtx.store

  return <LiveStoreContext.Provider value={storeCtx as TODO}>{children}</LiveStoreContext.Provider>
}

const useCreateStore = ({
  schema,
  storeId,
  otelOptions,
  boot,
  adapter,
  batchUpdates,
  disableDevtools,
  signal,
  context,
  params,
  confirmUnsavedChanges,
  syncPayload,
  debug,
}: CreateStoreOptions<LiveStoreSchema> & {
  signal?: AbortSignal | undefined
  otelOptions?: Partial<OtelOptions> | undefined
}) => {
  const [_, rerender] = React.useState(0)
  const ctxValueRef = React.useRef<{
    value: StoreContext_ | BootStatus
    componentScope: Scope.CloseableScope | undefined
    shutdownDeferred: ShutdownDeferred | undefined
    /** Used to wait for the previous shutdown deferred to fully complete before creating a new one */
    previousShutdownDeferred: ShutdownDeferred | undefined
    counter: number
  }>({
    value: { stage: 'loading' },
    componentScope: undefined,
    shutdownDeferred: undefined,
    previousShutdownDeferred: undefined,
    counter: 0,
  })
  const debugInstanceId = debug?.instanceId

  // console.debug(`useCreateStore (${ctxValueRef.current.counter})`, ctxValueRef.current.value.stage)

  const inputPropsCacheRef = React.useRef({
    schema,
    otelOptions,
    boot,
    adapter,
    batchUpdates,
    disableDevtools,
    signal,
    context,
    params,
    confirmUnsavedChanges,
    syncPayload,
    debugInstanceId,
  })

  const interrupt = (
    componentScope: Scope.CloseableScope,
    shutdownDeferred: ShutdownDeferred,
    error: StoreInterrupted,
  ) =>
    Effect.gen(function* () {
      // console.log('[@livestore/livestore/react] interupting', error)
      yield* Scope.close(componentScope, Exit.fail(error))
      yield* Deferred.fail(shutdownDeferred, error)
    }).pipe(
      Effect.tapErrorCause((cause) => Effect.logDebug('[@livestore/livestore/react] interupting', cause)),
      Effect.runFork,
    )

  const inputPropChanges = {
    schema: inputPropsCacheRef.current.schema !== schema,
    otelOptions: inputPropsCacheRef.current.otelOptions !== otelOptions,
    boot: inputPropsCacheRef.current.boot !== boot,
    adapter: inputPropsCacheRef.current.adapter !== adapter,
    batchUpdates: inputPropsCacheRef.current.batchUpdates !== batchUpdates,
    disableDevtools: inputPropsCacheRef.current.disableDevtools !== disableDevtools,
    signal: inputPropsCacheRef.current.signal !== signal,
    context: inputPropsCacheRef.current.context !== context,
    params: inputPropsCacheRef.current.params !== params,
    confirmUnsavedChanges: inputPropsCacheRef.current.confirmUnsavedChanges !== confirmUnsavedChanges,
    syncPayload: inputPropsCacheRef.current.syncPayload !== syncPayload,
    debugInstanceId: inputPropsCacheRef.current.debugInstanceId !== debugInstanceId,
  }

  if (
    inputPropChanges.schema ||
    inputPropChanges.otelOptions ||
    inputPropChanges.boot ||
    inputPropChanges.adapter ||
    inputPropChanges.batchUpdates ||
    inputPropChanges.disableDevtools ||
    inputPropChanges.signal ||
    inputPropChanges.context ||
    inputPropChanges.params ||
    inputPropChanges.confirmUnsavedChanges ||
    inputPropChanges.syncPayload
  ) {
    inputPropsCacheRef.current = {
      schema,
      otelOptions,
      boot,
      adapter,
      batchUpdates,
      disableDevtools,
      signal,
      context,
      params,
      confirmUnsavedChanges,
      syncPayload,
      debugInstanceId,
    }
    if (ctxValueRef.current.componentScope !== undefined && ctxValueRef.current.shutdownDeferred !== undefined) {
      const changedInputProps = Object.keys(inputPropChanges).filter(
        (key) => inputPropChanges[key as keyof typeof inputPropChanges],
      )

      interrupt(
        ctxValueRef.current.componentScope,
        ctxValueRef.current.shutdownDeferred,
        new StoreInterrupted({ reason: `re-rendering due to changed input props: ${changedInputProps.join(', ')}` }),
      )
      ctxValueRef.current.componentScope = undefined
      ctxValueRef.current.shutdownDeferred = undefined
    }
    ctxValueRef.current = {
      value: { stage: 'loading' },
      componentScope: undefined,
      shutdownDeferred: undefined,
      previousShutdownDeferred: ctxValueRef.current.shutdownDeferred,
      counter: ctxValueRef.current.counter + 1,
    }
  }

  React.useEffect(() => {
    const counter = ctxValueRef.current.counter

    const setContextValue = (value: StoreContext_ | BootStatus) => {
      if (ctxValueRef.current.counter !== counter) return
      ctxValueRef.current.value = value
      rerender((c) => c + 1)
    }

    signal?.addEventListener('abort', () => {
      if (
        ctxValueRef.current.componentScope !== undefined &&
        ctxValueRef.current.shutdownDeferred !== undefined &&
        ctxValueRef.current.counter === counter
      ) {
        interrupt(
          ctxValueRef.current.componentScope,
          ctxValueRef.current.shutdownDeferred,
          new StoreInterrupted({ reason: 'Aborted via provided AbortController' }),
        )
        ctxValueRef.current.componentScope = undefined
        ctxValueRef.current.shutdownDeferred = undefined
      }
    })

    const cancel = Effect.gen(function* () {
      // Wait for the previous store to fully shutdown before creating a new one
      if (ctxValueRef.current.previousShutdownDeferred) {
        yield* Deferred.await(ctxValueRef.current.previousShutdownDeferred)
      }

      const componentScope = yield* Scope.make().pipe(Effect.acquireRelease(Scope.close))
      const shutdownDeferred = yield* makeShutdownDeferred

      ctxValueRef.current.componentScope = componentScope
      ctxValueRef.current.shutdownDeferred = shutdownDeferred

      yield* Effect.gen(function* () {
        const store = yield* createStore({
          schema,
          storeId,
          boot,
          adapter,
          batchUpdates,
          disableDevtools,
          shutdownDeferred,
          context,
          params,
          confirmUnsavedChanges,
          syncPayload,
          onBootStatus: (status) => {
            if (ctxValueRef.current.value.stage === 'running' || ctxValueRef.current.value.stage === 'error') return
            // NOTE sometimes when status come in in rapid succession, only the last value will be rendered by React
            setContextValue(status)
          },
          debug: { instanceId: debugInstanceId },
        }).pipe(Effect.tapErrorCause((cause) => Deferred.failCause(shutdownDeferred, cause)))

        setContextValue({ stage: 'running', store })
      }).pipe(Scope.extend(componentScope), Effect.forkIn(componentScope))

      const shutdownContext = (cause: IntentionalShutdownCause | StoreInterrupted) =>
        Effect.sync(() => setContextValue({ stage: 'shutdown', cause }))

      yield* Deferred.await(shutdownDeferred).pipe(
        Effect.tapErrorCause((cause) => Effect.logDebug('[@livestore/livestore/react] shutdown', Cause.pretty(cause))),
        Effect.catchTag('LiveStore.IntentionalShutdownCause', (cause) => shutdownContext(cause)),
        Effect.catchTag('LiveStore.StoreInterrupted', (cause) => shutdownContext(cause)),
        Effect.tapError((error) => Effect.sync(() => setContextValue({ stage: 'error', error }))),
        Effect.tapDefect((defect) => Effect.sync(() => setContextValue({ stage: 'error', error: defect }))),
        Effect.exit,
      )
    }).pipe(
      Effect.scoped,
      Effect.withSpan('@livestore/react:useCreateStore'),
      LS_DEV ? TaskTracing.withAsyncTaggingTracing((name: string) => (console as any).createTask(name)) : identity,
      provideOtel({ parentSpanContext: otelOptions?.rootSpanContext, otelTracer: otelOptions?.tracer }),
      Effect.tapCauseLogPretty,
      Effect.annotateLogs({ thread: 'window' }),
      Effect.provide(Logger.prettyWithThread('window')),
      Logger.withMinimumLogLevel(LogLevel.Debug),
      Effect.runCallback,
    )

    return () => {
      cancel()

      if (ctxValueRef.current.componentScope !== undefined && ctxValueRef.current.shutdownDeferred !== undefined) {
        interrupt(
          ctxValueRef.current.componentScope,
          ctxValueRef.current.shutdownDeferred,
          new StoreInterrupted({ reason: 'unmounting component' }),
        )
        ctxValueRef.current.componentScope = undefined
        ctxValueRef.current.shutdownDeferred = undefined
      }
    }
  }, [
    schema,
    otelOptions,
    boot,
    adapter,
    batchUpdates,
    disableDevtools,
    signal,
    storeId,
    context,
    params,
    confirmUnsavedChanges,
    syncPayload,
    debugInstanceId,
  ])

  return ctxValueRef.current.value
}
