// packages/@livestore/react/src/LiveStoreContext.ts
import type { LiveStoreContextRunning } from '@livestore/livestore'
import React from 'react'

import type { useClientDocument } from './useClientDocument.js'
import type { useQuery } from './useQuery.js'

export type ReactApi = {
  useQuery: typeof useQuery
  useClientDocument: typeof useClientDocument
}

export const LiveStoreContext = React.createContext<
  { stage: 'running'; store: LiveStoreContextRunning['store'] & ReactApi } | undefined
>(undefined)

// packages/@livestore/solid/src/LiveStoreContext.ts
import type { LiveStoreContextRunning } from '@livestore/livestore'

import type { useClientDocument } from './useClientDocument.ts'
import type { useQuery } from './useQuery.ts'
import { createContext } from 'solid-js'

export type SolidApi = {
  useQuery: typeof useQuery
  useClientDocument: typeof useClientDocument
}

export const LiveStoreContext = createContext<
  { stage: 'running'; store: LiveStoreContextRunning['store'] & SolidApi } | undefined
>(undefined)
