// docs/src/content/_assets/code/reference/framework-integrations/vue/provider.vue
<script setup lang="ts">
import { makeInMemoryAdapter } from '@livestore/adapter-web'

import { schema } from './schema.ts'

const adapter = makeInMemoryAdapter()
const storeId = 'demo-store'
const _options = { schema, adapter, storeId }
</script>

<template>
  <LiveStoreProvider :options="options">
    <template #loading>
      <div>Loading LiveStore...</div>
    </template>
    <slot />
  </LiveStoreProvider>
</template>

// docs/src/content/_assets/code/reference/framework-integrations/react/provider.tsx
import { makeInMemoryAdapter } from '@livestore/adapter-web'
import { LiveStoreProvider } from '@livestore/react'
import type { FC, ReactNode } from 'react'
import { unstable_batchedUpdates as batchUpdates } from 'react-dom'

import { schema } from './schema.ts'

const adapter = makeInMemoryAdapter()

export const Root: FC<{ children: ReactNode }> = ({ children }) => (
  <LiveStoreProvider schema={schema} adapter={adapter} batchUpdates={batchUpdates}>
    {children}
  </LiveStoreProvider>
)
