// docs/src/content/_assets/code/reference/framework-integrations/vue/use-client-document.vue
<script setup lang="ts">
import { useClientDocument } from 'vue-livestore'

import { tables } from './schema.ts'

const { newTodoText, filter } = useClientDocument(tables.uiState)

void newTodoText
void filter

void newTodoText
void filter
</script>

<template>
  <div>
    <input type="text" v-model="newTodoText" />

    <select v-model="filter">
      <option value="all">All</option>
      <option value="active">Active</option>
      <option value="completed">Completed</option>
    </select>
  </div>
</template>

// docs/src/content/_assets/code/reference/framework-integrations/react/use-client-document.tsx
import { useStore } from '@livestore/react'
import type { FC } from 'react'

import { tables } from './schema.ts'

export const TodoItem: FC<{ id: string }> = ({ id }) => {
  const { store } = useStore()
  const [todo, updateTodo] = store.useClientDocument(tables.uiState, id)

  return (
    <button type="button" onClick={() => updateTodo({ text: 'Hello, world!' })}>
      {todo.text}
    </button>
  )
}
