// examples/web-todomvc-solid/src/components/Header.tsx
import type { Component } from 'solid-js'

import { uiState$ } from '../livestore/queries.ts'
import { events } from '../livestore/schema.ts'
import { useAppStore } from '../livestore/store.ts'

export const Header: Component = () => {
  const store = useAppStore()
  const uiState = store.useQuery(uiState$)

  const updateNewTodoText = (text: string) => {
    store()?.commit(events.uiStateSet({ newTodoText: text }))
  }

  const createTodo = () => {
    const text = uiState()?.newTodoText
    if (text?.trim()) {
      store()?.commit(events.todoCreated({ id: crypto.randomUUID(), text }), events.uiStateSet({ newTodoText: '' }))
    }
  }

  return (
    <header class="header">
      <h1>TodoMVC</h1>
      <input
        class="new-todo"
        placeholder="What needs to be done?"
        autofocus={true}
        value={uiState()?.newTodoText ?? ''}
        onInput={(e) => updateNewTodoText(e.currentTarget.value)}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            createTodo()
          }
        }}
      />
    </header>
  )
}

// examples/web-todomvc-experimental/src/components/Header.tsx
import type React from 'react'
import { uiState$ } from '../livestore/queries.ts'
import { events } from '../livestore/schema.ts'
import { useAppStore } from '../livestore/store.ts'

export const Header: React.FC = () => {
  const store = useAppStore()
  const { newTodoText } = store.useQuery(uiState$)

  const updatedNewTodoText = (text: string) => store.commit(events.uiStateSet({ newTodoText: text }))
  const handleTodoCreated = () =>
    store.commit(
      events.todoCreated({ id: crypto.randomUUID(), text: newTodoText.trim() }),
      events.uiStateSet({ newTodoText: '' }),
    )

  return (
    <header className="header">
      <h1>TodoMVC</h1>
      <input
        className="new-todo"
        placeholder="What needs to be done?"
        value={newTodoText}
        onChange={(e) => updatedNewTodoText(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            handleTodoCreated()
          }
        }}
      />
    </header>
  )
}
