// docs/src/content/_assets/code/reference/solid-integration/components/MainSection.tsx
/** biome-ignore-all lint/a11y/noLabelWithoutControl: TODO 🫠 */
/** @jsxImportSource solid-js */
import { query } from '@livestore/solid'
import { type Component, For } from 'solid-js'

import { visibleTodos$ } from '../livestore/queries.ts'
import { events, type tables } from '../livestore/schema.ts'
import { store } from '../livestore/store.ts'

export const MainSection: Component = () => {
  const todos = query(visibleTodos$, [] as (typeof tables.todos.Type)[])
  const todoItems = () => todos() ?? ([] as (typeof tables.todos.Type)[])

  const toggleTodo = ({ id, completed }: typeof tables.todos.Type) =>
    store()?.commit(completed ? events.todoUncompleted({ id }) : events.todoCompleted({ id }))

  const deleteTodo = (id: string) => store()?.commit(events.todoDeleted({ id, deletedAt: new Date() }))

  return (
    <section class="main">
      <ul class="todo-list">
        <For each={todoItems()}>
          {(todo: typeof tables.todos.Type) => (
            <li>
              <div class="view">
                <input type="checkbox" class="toggle" checked={todo.completed} onChange={() => toggleTodo(todo)} />
                <label>{todo.text}</label>
                <button type="button" class="destroy" onClick={() => deleteTodo(todo.id)} />
              </div>
            </li>
          )}
        </For>
      </ul>
    </section>
  )
}

// examples/web-todomvc-react-router/src/components/MainSection.tsx
import { queryDb } from '@livestore/livestore'
import { useStore } from '@livestore/react'
import React from 'react'

import { uiState$ } from '../livestore/queries.ts'
import { events, tables } from '../livestore/schema.ts'

const visibleTodos$ = queryDb(
  (get) => {
    const { filter } = get(uiState$)
    return tables.todos.where({
      deletedAt: null,
      completed: filter === 'all' ? undefined : filter === 'completed',
    })
  },
  { label: 'visibleTodos' },
)

export const MainSection: React.FC = () => {
  const { store } = useStore()

  const toggleTodo = React.useCallback(
    ({ id, completed }: typeof tables.todos.Type) =>
      store.commit(completed ? events.todoUncompleted({ id }) : events.todoCompleted({ id })),
    [store],
  )

  const visibleTodos = store.useQuery(visibleTodos$)

  return (
    <section className="main">
      <ul className="todo-list">
        {visibleTodos.map((todo) => (
          <li key={todo.id}>
            <div className="state">
              <input type="checkbox" className="toggle" checked={todo.completed} onChange={() => toggleTodo(todo)} />
              {/** biome-ignore lint/a11y/noLabelWithoutControl: otherwise breaks TODO MVC CSS 🙈 */}
              <label>{todo.text}</label>
              <button
                type="button"
                className="destroy"
                onClick={() => store.commit(events.todoDeleted({ id: todo.id, deletedAt: new Date() }))}
              />
            </div>
          </li>
        ))}
      </ul>
    </section>
  )
}
