// examples/src/todomvc-sync-electric/src/components/Footer.tsx
import { query, sql } from '@livestore/livestore'
import { useQuery, useRow, useStore } from '@livestore/react'
import { Schema } from 'effect'
import React from 'react'

import { mutations, tables } from '../schema/index.js'
import type { Filter } from '../types.js'

const incompleteCount$ = query(sql`select count(*) as c from todos where completed = false and deleted is null`, {
  schema: Schema.Struct({ c: Schema.Number }).pipe(Schema.pluck('c'), Schema.Array, Schema.headOrElse()),
  label: 'incompleteCount',
})

export const Footer: React.FC = () => {
  const { store } = useStore()
  const sessionId = store.sessionId
  const [{ filter }] = useRow(tables.app, sessionId)
  const incompleteCount = useQuery(incompleteCount$)

  const setFilter = (filter: Filter) => store.mutate(mutations.setFilter({ filter, sessionId }))

  return (
    <footer className="footer">
      <span className="todo-count">{incompleteCount} items left</span>
      <ul className="filters">
        <li>
          <a href="#/" className={filter === 'all' ? 'selected' : ''} onClick={() => setFilter('all')}>
            All
          </a>
        </li>
        <li>
          <a href="#/" className={filter === 'active' ? 'selected' : ''} onClick={() => setFilter('active')}>
            Active
          </a>
        </li>
        <li>
          <a href="#/" className={filter === 'completed' ? 'selected' : ''} onClick={() => setFilter('completed')}>
            Completed
          </a>
        </li>
      </ul>
      <button
        className="clear-completed"
        onClick={() => store.mutate(mutations.clearCompleted({ deleted: Date.now() }))}
      >
        Clear completed
      </button>
    </footer>
  )
}

// examples/src/todomvc-solid/src/components/Footer.tsx
import { Schema } from 'effect'
import { querySQL, sql } from '@livestore/livestore'
import { query, row } from '@livestore/solid'
import type { Component } from 'solid-js'

import { mutations, tables } from '../schema/index.js'
import { store } from '../store.jsx'
import type { Filter } from '../types.js'

const sessionId = store?.()?.sessionId ??'default'; 

const incompleteCount$ = querySQL(sql`select count(*) as c from todos where completed = false and deleted is null`, {
  schema: Schema.Struct({ c: Schema.Number }).pipe(Schema.pluck('c'), Schema.Array, Schema.headOrElse()),
  label: 'incompleteCount',
})

export const Footer: Component = () => {
  const appRow = row(tables.app, sessionId)
  const incompleteCount = query(incompleteCount$, 0)

  const setFilter = (filter: Filter) => store()?.mutate(mutations.setFilter({ filter, sessionId }))

  return (
    <footer class="footer">
      <span class="todo-count">{incompleteCount()} items left</span>
      <ul class="filters">
        <li>
          <a
            href="#/"
            class={appRow()?.filter === 'all' ? 'selected' : ''}
            onClick={() => {
              setFilter('all')
            }}
          >
            All
          </a>
        </li>
        <li>
          <a
            href="#/"
            class={appRow()?.filter === 'active' ? 'selected' : ''}
            onClick={() => {
              setFilter('active')
            }}
          >
            Active
          </a>
        </li>
        <li>
          <a
            href="#/"
            class={appRow()?.filter === 'completed' ? 'selected' : ''}
            onClick={() => {
              setFilter('completed')
            }}
          >
            Completed
          </a>
        </li>
      </ul>
      <button
        class="clear-completed"
        onClick={() => {
          store()?.mutate(mutations.clearCompleted({ deleted: Date.now() }))
        }}
      >
        Clear completed
      </button>
    </footer>
  )
}
