// examples/src/web-todomvc-experimental/src/components/Header.tsx
import { useQuery, useStore } from '@livestore/react'
import React from 'react'

import { uiState$ } from '../livestore/queries.js'
import { events } from '../livestore/schema.js'

export const Header: React.FC = () => {
  const { store } = useStore()
  const { newTodoText } = useQuery(uiState$)

  const updatedNewTodoText = (text: string) => store.commit(events.uiStateSet({ newTodoText: text }))
  const handleTodoCreated = () =>
    store.commit(
      events.todoCreated({ id: crypto.randomUUID(), text: newTodoText.trim() }),
      events.uiStateSet({ newTodoText: '' }),
    )

  return (
    <header className="header">
      <h1>TodoMVC</h1>
      <input
        className="new-todo"
        placeholder="What needs to be done?"
        autoFocus={true}
        value={newTodoText}
        onChange={(e) => updatedNewTodoText(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            handleTodoCreated()
          }
        }}
      ></input>
    </header>
  )
}

// examples/web-todomvc-svelte/src/components/Header.svelte
<script lang="ts">
  import { events } from '../livestore/schema.js'
  import { uiState$ } from '../livestore/queries.js'
  import { store } from '../livestore/store';

  let { newTodoText } = $derived(store.query(uiState$))
  const updatedNewTodoText = (text: string) => store.commit(events.uiStateSet({ newTodoText: text }))
  const todoCreated = () =>
    store.commit(
      events.todoCreated({ id: crypto.randomUUID(), text: newTodoText }),
      events.uiStateSet({ newTodoText: '' }),
    )
</script>

<header class="header">
  <h1>TodoMVC</h1>
  <input
    class="new-todo"
    placeholder="What needs to be done?"
    autofocus
    bind:value={() => newTodoText, (v) => updatedNewTodoText(v)}
    onkeydown={(e) => {
      if (e.key === 'Enter') {
        todoCreated()
      }
    }}
  />
</header>
