// examples/src/todomvc-solid/src/components/MainSection.tsx
import { queryDb } from '@livestore/livestore'
import { query } from '@livestore/solid'
import { type Component, Index } from 'solid-js'

import { uiState$ } from '../livestore/queries.js'
import { events, tables, type Todo } from '../livestore/schema.js'
import { store } from '../livestore/store.js'

const visibleTodos$ = queryDb(
  (get) => {
    const { filter } = get(uiState$)
    return tables.todos.where({
      deletedAt: null,
      completed: filter === 'all' ? undefined : filter === 'completed',
    })
  },
  { label: 'visibleTodos' },
)

export const MainSection: Component = () => {
  const toggleTodo = ({ id, completed }: Todo) => {
    store()?.commit(completed ? events.todoUncompleted({ id }) : events.todoCompleted({ id }))
  }

  const visibleTodos = query(visibleTodos$, [])

  return (
    <section class="main">
      <ul class="todo-list">
        <Index each={visibleTodos() || []}>
          {(todo) => (
            <li onClick={() => toggleTodo(todo())}>
              <div class="view">
                <input title="check " type="checkbox" class="toggle" checked={todo().completed} />
                <label>{todo().text}</label>
                <button
                  title="button"
                  class="destroy"
                  onClick={(e) => {
                    e.stopPropagation()
                    store()?.commit(events.todoDeleted({ id: todo().id, deletedAt: new Date() }))
                  }}
                ></button>
              </div>
            </li>
          )}
        </Index>
      </ul>
    </section>
  )
}

// examples/web-todomvc-svelte/src/components/MainSection.svelte
<script lang="ts">
  import { uiState$ } from '../livestore/queries'
  import { events, tables } from '../livestore/schema'
  import { store } from '../livestore/store';
  import { queryDb } from '@livestore/livestore'

  const visibleTodos$ = queryDb(
    (get) => {
      const { filter } = get(uiState$)
      return tables.todos.where({
        deletedAt: null,
        completed: filter === 'all' ? undefined : filter === 'completed',
      })
    },
    { label: 'visibleTodos' },
  )
</script>

<section class="main">
  <ul class="todo-list">
    {#each store.query(visibleTodos$) as todo (todo.id)}
      <li>
        <div class="state">
          <input
            id="toggle-{todo.id}"
            type="checkbox"
            class="toggle"
            checked={todo.completed}
            onchange={() => store.commit(todo.completed ? events.todoUncompleted(todo) : events.todoCompleted(todo))}
          />
          <label for="toggle-{todo.id}">{todo.text}</label>
          <button
            aria-label="Delete"
            class="destroy"
            onclick={() => store.commit(events.todoDeleted({ id: todo.id, deletedAt: new Date() }))}
          ></button>
        </div>
      </li>
    {/each}
  </ul>
</section>
