// examples/src/web-todomvc-solid/src/components/Header.tsx
import { query } from '@livestore/solid'
import type { Component } from 'solid-js'

import { uiState$ } from '../livestore/queries.js'
import { events } from '../livestore/schema.js'
import { store } from '../livestore/store.js'

export const Header: Component = () => {
  const newRow = query(uiState$, { filter: 'all', newTodoText: '' })

  return (
    <header class="header">
      <h1>TodoMVC</h1>
      <input
        class="new-todo"
        placeholder="What needs to be done?"
        autofocus={true}
        value={newRow()?.newTodoText ?? ''}
        onChange={(e) => {
          store()?.commit(events.uiStateSet({ newTodoText: e.target.value }))
        }}
        onKeyDown={(e) => {
          if (e.key === 'Enter' && e.currentTarget.value.trim()) {
            store()?.commit(
              events.todoCreated({ id: crypto.randomUUID(), text: e.currentTarget.value }),
              events.uiStateSet({ newTodoText: '' }),
            )
          }
        }}
      ></input>
    </header>
  )
}

// examples/src/web-todomvc-experimental/src/components/Header.tsx
import { useQuery, useStore } from '@livestore/react'
import React from 'react'

import { uiState$ } from '../livestore/queries.js'
import { events } from '../livestore/schema.js'

export const Header: React.FC = () => {
  const { store } = useStore()
  const { newTodoText } = useQuery(uiState$)

  const updatedNewTodoText = (text: string) => store.commit(events.uiStateSet({ newTodoText: text }))
  const handleTodoCreated = () =>
    store.commit(
      events.todoCreated({ id: crypto.randomUUID(), text: newTodoText.trim() }),
      events.uiStateSet({ newTodoText: '' }),
    )

  return (
    <header className="header">
      <h1>TodoMVC</h1>
      <input
        className="new-todo"
        placeholder="What needs to be done?"
        autoFocus={true}
        value={newTodoText}
        onChange={(e) => updatedNewTodoText(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            handleTodoCreated()
          }
        }}
      ></input>
    </header>
  )
}
