// examples/web-todomvc-svelte/src/components/Header.svelte
<script lang="ts">
  import { events } from '../livestore/schema.js'
  import { uiState$ } from '../livestore/queries.js'
  import { store } from '../livestore/store';

  let { newTodoText } = $derived(store.query(uiState$))
  const updatedNewTodoText = (text: string) => store.commit(events.uiStateSet({ newTodoText: text }))
  const todoCreated = () =>
    store.commit(
      events.todoCreated({ id: crypto.randomUUID(), text: newTodoText }),
      events.uiStateSet({ newTodoText: '' }),
    )
</script>

<header class="header">
  <h1>TodoMVC</h1>
  <input
    class="new-todo"
    placeholder="What needs to be done?"
    autofocus
    bind:value={() => newTodoText, (v) => updatedNewTodoText(v)}
    onkeydown={(e) => {
      if (e.key === 'Enter') {
        todoCreated()
      }
    }}
  />
</header>

// examples/web-todomvc-sync-electric/src/components/Header.tsx
import type React from 'react'
import { uiState$ } from '../livestore/queries.ts'
import { events } from '../livestore/schema.ts'
import { useAppStore } from '../livestore/store.ts'

export const Header: React.FC = () => {
  const store = useAppStore()
  const { newTodoText } = store.useQuery(uiState$)

  const updatedNewTodoText = (text: string) => store.commit(events.uiStateSet({ newTodoText: text }))

  const todoCreated = () =>
    store.commit(
      events.todoCreated({ id: crypto.randomUUID(), text: newTodoText }),
      events.uiStateSet({ newTodoText: '' }),
    )

  return (
    <header className="header">
      <h1>TodoMVC</h1>
      <input
        className="new-todo"
        placeholder="What needs to be done?"
        value={newTodoText}
        onChange={(e) => updatedNewTodoText(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            todoCreated()
          }
        }}
      />
    </header>
  )
}
