// examples/src/todomvc-solid/src/components/Header.tsx
import { row } from '@livestore/solid'
import type { Component } from 'solid-js'

import { mutations, tables } from '../schema/index.js'
import { store } from '../store.js'

const sessionId = store()?.sessionId ?? 'default'

export const Header: Component = () => {
  const newRow = row(tables.app, sessionId)

  return (
    <header class="header">
      <h1>TodoMVC</h1>
      <input
        class="new-todo"
        placeholder="What needs to be done?"
        autofocus={true}
        value={newRow()?.newTodoText ?? ''}
        onChange={(e) => {
          store()?.mutate(
            mutations.updateNewTodoText({
              text: e.target.value,
              sessionId,
            }),
          )
        }}
        onKeyDown={(e) => {
          if (e.key === 'Enter' && e.currentTarget.value.trim()) {
            store()?.mutate(
              mutations.addTodo({ id: crypto.randomUUID(), text: e.currentTarget.value }),
              mutations.updateNewTodoText({ text: '', sessionId }),
            )
          }
        }}
      ></input>
    </header>
  )
}

// examples/standalone/todomvc-experimental/src/components/Header.tsx
import { useQuery, useStore } from '@livestore/react'
import React from 'react'

import { app$ } from '../livestore/queries.js'
import { mutations } from '../livestore/schema.js'

export const Header: React.FC = () => {
  const { store } = useStore()
  const sessionId = store.sessionId
  const { newTodoText } = useQuery(app$)

  const updateNewTodoText = (text: string) => store.mutate(mutations.updateNewTodoText({ text, sessionId }))
  const addTodo = () =>
    store.mutate(
      mutations.addTodo({ id: crypto.randomUUID(), text: newTodoText }),
      mutations.updateNewTodoText({ text: '', sessionId }),
    )

  return (
    <header className="header">
      <h1>TodoMVC</h1>
      <input
        className="new-todo"
        placeholder="What needs to be done?"
        autoFocus={true}
        value={newTodoText}
        onChange={(e) => updateNewTodoText(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            addTodo()
          }
        }}
      ></input>
    </header>
  )
}
