// examples/web-todomvc-sync-cf/src/components/MainSection.tsx
import { queryDb } from '@livestore/livestore'
import { useStore } from '@livestore/react'
import React from 'react'

import { uiState$ } from '../livestore/queries.js'
import { events, tables } from '../livestore/schema.js'

const visibleTodos$ = queryDb(
  (get) => {
    const { filter } = get(uiState$)
    return tables.todos.where({
      deletedAt: null,
      completed: filter === 'all' ? undefined : filter === 'completed',
    })
  },
  { label: 'visibleTodos' },
)

export const MainSection: React.FC = () => {
  const { store } = useStore()

  const toggleTodo = React.useCallback(
    ({ id, completed }: typeof tables.todos.Type) =>
      store.commit(completed ? events.todoUncompleted({ id }) : events.todoCompleted({ id })),
    [store],
  )

  const visibleTodos = store.useQuery(visibleTodos$)

  return (
    <section className="main">
      <ul className="todo-list">
        {visibleTodos.map((todo) => (
          <li key={todo.id}>
            <div className="state">
              <label>
                <input type="checkbox" className="toggle" checked={todo.completed} onChange={() => toggleTodo(todo)} />
                {todo.text}
              </label>
              <button
                type="button"
                className="destroy"
                onClick={() => store.commit(events.todoDeleted({ id: todo.id, deletedAt: new Date() }))}
              />
            </div>
          </li>
        ))}
      </ul>
    </section>
  )
}

// examples/src/web-todomvc-svelte/src/lib/components/main-section.svelte
<script module lang="ts">
  const visibleTodos$ = queryDb(
    (get) => {
      const { filter } = get(uiState$)
      return tables.todos.where({
        deletedAt: null,
        completed: filter === 'all' ? undefined : filter === 'completed',
      })
    },
    { label: 'visibleTodos' },
  )
</script>

<script lang="ts">
  import { uiState$ } from '$lib/livestore/queries'
  import { events, schema, tables } from '$lib/livestore/schema'
  import { queryDb } from '@livestore/livestore'
  import type { SvelteStore } from '@livestore/svelte'

  let { store }: { store: SvelteStore<typeof schema> } = $props()

  const toggleTodo = ({ id, completed }: typeof tables.todos.Type) =>
    store.commit(completed ? events.todoUncompleted({ id }) : events.todoCompleted({ id }))

  const visibleTodos = $derived.by(store.createQuery(visibleTodos$))
</script>

<section class="main">
  <ul class="todo-list">
    {#each visibleTodos as todo (todo.id)}
      <li>
        <div class="state">
          <input
            id="toggle-{todo.id}"
            type="checkbox"
            class="toggle"
            checked={todo.completed}
            onchange={() => toggleTodo(todo)}
          />
          <label for="toggle-{todo.id}">{todo.text}</label>
          <button
            aria-label="Delete"
            class="destroy"
            onclick={() => store.commit(events.todoDeleted({ id: todo.id, deletedAt: new Date() }))}
          ></button>
        </div>
      </li>
    {/each}
  </ul>
</section>
