// packages/@livestore/solid/src/LiveStoreContext.ts
import { createContext, useContext } from "solid-js";
import type { Store, LiveStoreSchema } from "@livestore/livestore";

export type LiveStoreContextValue = {
  store: Store<LiveStoreSchema>;
};

export const LiveStoreContext = createContext<LiveStoreContextValue>();

export function useLiveStore(): Store<LiveStoreSchema> {
  const context = useContext(LiveStoreContext);
  if (!context) {
    throw new Error("useLiveStore must be used within a <LiveStoreProvider>");
  }
  return context.store;
}

// packages/@livestore/livestore/src/react/LiveStoreContext.ts
import React, { useContext } from 'react'

import type { LiveStoreContext as LiveStoreContext_ } from '../effect/LiveStore.js'

export const LiveStoreContext = React.createContext<LiveStoreContext_ | undefined>(undefined)

export const useStore = (): LiveStoreContext_ => {
  const storeContext = useContext(LiveStoreContext)

  if (storeContext === undefined) {
    throw new Error(`useStore can only be used inside StoreContext.Provider`)
  }

  if (storeContext.stage !== 'running') {
    throw new Error(`useStore can only be used after the store is running`)
  }

  return storeContext
}
